"""
Reads data/parcels/parcels.json (hand-maintained facts) plus each parcel's
boundary CSV, and generates site/data.js for the static archive site.

Usage: python scripts/build_site_data.py
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARCELS_JSON = ROOT / "data" / "parcels" / "parcels.json"
PROPERTY_NOTES_JSON = ROOT / "data" / "parcels" / "property_notes.json"
SITE_DATA_JS = ROOT / "site" / "data.js"

SVG_BOX = 200  # viewBox size for the boundary shape thumbnail
SVG_PAD = 12


def boundary_csv_path(parcel_id):
    return ROOT / "data" / "parcels" / f"{parcel_id}_boundary.csv"


def load_boundary_points(csv_path):
    points = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            points.append((float(row["X"]), float(row["Y"])))
    return points


def normalize_to_svg(points):
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    w = maxx - minx or 1
    h = maxy - miny or 1
    scale = (SVG_BOX - 2 * SVG_PAD) / max(w, h)
    # center within the box, flip Y so north is up (geo Y grows north, svg y grows down)
    offx = (SVG_BOX - w * scale) / 2
    offy = (SVG_BOX - h * scale) / 2
    svg_points = []
    for x, y in points:
        sx = (x - minx) * scale + offx
        sy = SVG_BOX - ((y - miny) * scale + offy)  # flip
        svg_points.append((round(sx, 1), round(sy, 1)))
    return svg_points


def main():
    parcels = json.loads(PARCELS_JSON.read_text(encoding="utf-8"))

    for parcel in parcels:
        place = parcel.get("place_name")
        qualifier = parcel.get("place_qualifier")
        if place and qualifier:
            parcel["display_name"] = f"{place} ({qualifier})"
        elif place:
            parcel["display_name"] = place
        else:
            parcel["display_name"] = parcel["id"].replace("_", " ").title()

        csv_path = boundary_csv_path(parcel["id"])
        if csv_path.exists():
            points = load_boundary_points(csv_path)
            svg_points = normalize_to_svg(points)
            parcel["boundary_svg_points"] = svg_points
            parcel["boundary_svg_viewbox"] = f"0 0 {SVG_BOX} {SVG_BOX}"
        else:
            parcel["boundary_svg_points"] = None

        # resolve image paths relative to the site/ folder (one level up)
        for img in parcel.get("images", []):
            img["site_relative_path"] = "../" + img["file"].replace("\\", "/")

        if parcel.get("boundary_geojson"):
            parcel["boundary_geojson_site_path"] = "../" + parcel["boundary_geojson"].replace("\\", "/")

    overview = build_overview(parcels)

    SITE_DATA_JS.parent.mkdir(parents=True, exist_ok=True)
    js_content = "// Auto-generated by scripts/build_site_data.py — do not hand-edit.\n"
    js_content += "const PARCELS = " + json.dumps(parcels, indent=2, ensure_ascii=False) + ";\n"
    js_content += "const OVERVIEW = " + json.dumps(overview, indent=2, ensure_ascii=False) + ";\n"
    SITE_DATA_JS.write_text(js_content, encoding="utf-8")
    print(f"Wrote {SITE_DATA_JS} with {len(parcels)} parcel(s).")


def build_overview(parcels):
    property_notes = {}
    if PROPERTY_NOTES_JSON.exists():
        property_notes = json.loads(PROPERTY_NOTES_JSON.read_text(encoding="utf-8"))

    total_area_m2 = sum(p.get("area_m2", 0) for p in parcels)

    locations = {}
    for p in parcels:
        place = p.get("place_name") or "Other"
        loc = locations.setdefault(place, {
            "place_name": place, "parcel_count": 0, "area_m2": 0.0,
            "trees_low": 0, "trees_high": 0,
        })
        loc["parcel_count"] += 1
        loc["area_m2"] += p.get("area_m2", 0)
        loc["trees_low"] += p.get("trees_low", 0)
        loc["trees_high"] += p.get("trees_high", 0)
    for loc in locations.values():
        loc["area_stremmata"] = round(loc["area_m2"] / 1000, 2)

    exact_tree_parcels = [
        {"name": p["display_name"], "count": p["trees_low"]}
        for p in parcels if p.get("trees_exact")
    ]

    all_seasons = [s for p in parcels for s in p.get("seasons", [])]
    total_oil_liters = sum(s.get("oil_liters", 0) or 0 for s in all_seasons)
    total_water_m3 = sum(s.get("water_m3", 0) or 0 for s in all_seasons)

    return {
        "display_name": "Xwrafia (Ola)",
        "total_parcels": len(parcels),
        "total_area_m2": round(total_area_m2, 2),
        "total_area_stremmata": round(total_area_m2 / 1000, 2),
        "total_area_ha": round(total_area_m2 / 10000, 3),
        "trees_low": sum(p.get("trees_low", 0) for p in parcels),
        "trees_high": sum(p.get("trees_high", 0) for p in parcels),
        "exact_tree_parcels": exact_tree_parcels,
        "locations": sorted(locations.values(), key=lambda l: -l["area_m2"]),
        "has_production_records": len(all_seasons) > 0,
        "total_oil_liters": total_oil_liters,
        "total_water_m3": total_water_m3,
        "map_image": "../data/parcels/imagery/overview_map.png",
        "owner_tree_estimate_low": property_notes.get("owner_tree_estimate_low"),
        "owner_tree_estimate_high": property_notes.get("owner_tree_estimate_high"),
        "owner_tree_estimate_note": property_notes.get("owner_tree_estimate_note"),
    }


if __name__ == "__main__":
    main()
